version: '3'
services:
  laravel.test:
    build:
      context: ./docker/8.0
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.0/app
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      LARAVEL_SAIL: 1
      WWWUSER: '${WWWUSER}'
      XDEBUG_CONFIG: 'client_port=9003'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
      - takeout
networks:
  sail:
    driver: bridge
  takeout:
    external:
      name: takeout
